TYPO3:
  CMS:
    Form:
      persistenceManager:
        allowedExtensionPaths:
          10: EXT:tw_nueww/Configuration/Yaml/Form/Forms/
      prototypes:
        standard:
          finishersDefinition:
            BlogComment:
              implementationClassName: 'Tollwerk\TwNueww\Domain\Finisher\BlogCommentFinisher'
        blog-comment:
          __inheritances:
            10: 'TYPO3.CMS.Form.prototypes.standard'
          formElementsDefinition:
            Form:
              renderingOptions:
                partialRootPaths:
                  100: 'EXT:tw_nueww/Resources/Private/Partials/FormFramework/Blog/Comment'
          finishersDefinition:
            BlogComment:
              implementationClassName: 'Tollwerk\TwNueww\Domain\Finisher\BlogCommentFinisher'