<?php
/**
 * Created by PhpStorm.
 * User: klaus
 * Date: 03.10.2017
 * Time: 13:17
 */

namespace Tollwerk\TwNueww\ViewHelpers\Form;


use TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper;

class FieldsByNameViewHelper extends AbstractViewHelper
{
    public function initializeArguments()
    {
        parent::initializeArguments(); // TODO: Change the autogenerated stub
        $this->registerArgument('elements', 'array', 'The form fields delivered by form framework', true);
    }

    public function render(){

        $elements = [];

        /**
         * @var \TYPO3\CMS\Form\Domain\Model\FormElements\GenericFormElement $element
         */
        foreach($this->arguments['elements'] as $element){
            $elements[$element->getIdentifier()] = $element;
        }

        return $elements;
    }
}